name: demo_book_reader
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

analyzer:
  errors:
    invalid_annotation_target: ignore

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  freezed_annotation: ^2.0.3
  json_annotation: ^4.7.0
  percent_indicator: ^4.0.1
  carousel_slider: ^4.1.1
  readmore: ^2.2.0
  syncfusion_flutter_charts: ^21.1.35
  intl: ^0.17.0
  file_picker: ^5.0.1
  dotted_border: ^2.0.0+2
  http: ^0.13.5
  vocsy_epub_viewer:
    path: ./packages/vocsy_epub_viewer
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  intl_phone_field: ^3.1.0
  syncfusion_flutter_datepicker: ^21.1.35
  image_picker: ^0.8.7+1
  cached_network_image: ^3.2.3
  const_date_time: ^1.0.2
  flutter_zalopay_sdk: ^0.1.13
  sprintf: ^7.0.0
  flutter_local_notifications: ^13.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  test: ^1.22.0
  mockito: ^5.4.0
  bloc_test: ^9.1.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/image/logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true
  assets:
    - assets/epub/
    - assets/image/
    - assets/image/ranking/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
